In [42]:
import pandas as pd

In [43]:
df = pd.read_table('SMSSpamCollection')
df.columns = ['label', 'sms_message']

for i, el in enumerate(df['label']):
    # if(i == 0):
        # df['label'][i] = '0' if df['label'][i] == 'ham' else '1'
        df.loc[i, 'label'] = '0' if df.loc[i, 'label'] == 'ham' else '1'
        # print(df['label'][0])   
    
df['label'] = df['label'].astype(int)

df.head()

   label                                        sms_message
0      0                      Ok lar... Joking wif u oni...
1      1  Free entry in 2 a wkly comp to win FA Cup fina...
2      0  U dun say so early hor... U c already then say...
3      0  Nah I don't think he goes to usf, he lives aro...
4      1  FreeMsg Hey there darling it's been 3 week's n...

In [44]:
#Step 1.2 - Implementing a Bag of Words from scratch by 4 steps

import string
from collections import Counter
import pprint
documents = ['Hello, how are you!',
             'Win money, win from home.',
             'Call me now.',
             'Hello, Call hello you tomorrow?']

lower_case_documents:list[str] = []
for sentence in documents:
    lower_case_documents.append(sentence.lower())

sans_punctuation_documents:list[str]= []
for sentence in lower_case_documents:
    clean_text = sentence.translate(str.maketrans('','',string.punctuation)).lower()
    sans_punctuation_documents.append(clean_text)

preprocessed_documents:list[list[str]] = []
for sentence in sans_punctuation_documents:
    preprocessed_documents.append(sentence.split())

frequency_list = []
for sentence in preprocessed_documents:
    frequency_list.append(dict(Counter(sentence)) )
    
pprint.pprint(frequency_list)

[{'are': 1, 'hello': 1, 'how': 1, 'you': 1},
 {'from': 1, 'home': 1, 'money': 1, 'win': 2},
 {'call': 1, 'me': 1, 'now': 1},
 {'call': 1, 'hello': 2, 'tomorrow': 1, 'you': 1}]

In [ ]:
#Implementing a Bag of Word with Skitlearn

from sklearn.feature_extraction.text import CountVectorizer

count_vector = CountVectorizer(lowercase=True, stop_words='english')

documents = ['Hello, how are you!',
                'Win money, win from home.',
                'Call me now.',
                'Hello, Call hello you tomorrow?']

pprint.pprint(documents)

# Essas duas linhas fazem a mesma coisa que #1
# count_vector.fit(documents)
# count_vector.get_feature_names_out()

# 1
count_vector.fit_transform(documents)

doc_array = count_vector.transform(documents).toarray()

frequency_matrix = pd.DataFrame(doc_array)

list_names = count_vector.get_feature_names_out().tolist()

frequency_matrix.columns = list_names


frequency_matrix
# print(count_vector.get_feature_names_out())
# print(doc_array)

['Hello, how are you!',
 'Win money, win from home.',
 'Call me now.',
 'Hello, Call hello you tomorrow?']

   hello  home  money  tomorrow  win
0      1     0      0         0    0
1      0     1      1         0    2
2      0     0      0         0    0
3      2     0      0         1    0